"""
Django settings for myproject project.
Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING — change in production
SECRET_KEY = "django-insecure-a6f*$eh4p!6=lh-+h#*)afw4*t^_5c*sp-is_7gq(=y!sxkyv_"

ALLOWED_HOSTS = ["*"]


# ============================
# CORS SETTINGS
# ============================
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:8000",
    "https://project-budgeting-fe.onrender.com",
    "https://projectbudgeting-merged-1.onrender.com",
]
CORS_ALLOW_CREDENTIALS = True


# ============================
# INSTALLED APPS
# ============================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",

    "accounts",
    "module",
    "product_group",
    "roles",
    "client",
]


# ============================
# MIDDLEWARE
# ============================
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",   # Correct placement
    "corsheaders.middleware.CorsMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "myproject.urls"


# ============================
# TEMPLATES
# ============================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # Tell Django to look for index.html in the frontend build directory
        "DIRS": [os.path.join(BASE_DIR.parent, "Project_Budgeting-FE-", "dist")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "myproject.wsgi.application"


# ============================
# DATABASE (SQLite for now)
# ============================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# ============================
# PASSWORD VALIDATION
# ============================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# ============================
# INTERNATIONALIZATION
# ============================
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# ============================
# REST FRAMEWORK + JWT
# ============================
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}


AUTH_USER_MODEL = "accounts.Account"


# ============================
# EMAIL SETTINGS
# ============================
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_HOST_USER = "vanumushashidhar@gmail.com"
EMAIL_HOST_PASSWORD = "qtye gvwm puhm twsa"  # SHOULD NOT BE IN CODE
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = "Your App <no-reply@yourdomain.com>"


# ============================
# CLOUDINARY STORAGE
# ============================
load_dotenv()
print("Cloud Name:", os.environ.get("CLOUDINARY_CLOUD_NAME"))
print("APiKey", os.environ.get("CLOUDINARY_API_KEY"))

CLOUDINARY_STORAGE = {
    "CLOUD_NAME": os.environ.get("CLOUDINARY_CLOUD_NAME"),
    "API_KEY": os.environ.get("CLOUDINARY_API_KEY"),
    "API_SECRET": os.environ.get("CLOUDINARY_API_SECRET"),
    "SECURE": True,
    "AUTHENTICATED": False,
}

DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"

MEDIA_ROOT = BASE_DIR / "media"


# ============================
# STATIC FILES + WHITENOISE
# ============================
STATIC_URL = "/static/"

# The directory where collectstatic will place all static files
STATIC_ROOT = os.path.join(BASE_DIR.parent, "staticfiles_build")

# The directories where collectstatic will look for static files to collect
STATICFILES_DIRS = [
    # The output of the React build process
    os.path.join(BASE_DIR.parent, "Project_Budgeting-FE-", "dist"),
]

# Use WhiteNoise for serving static files in production
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Required for Django to find files in dist/
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
import os
print("🟦 BASE_DIR:", BASE_DIR)
print("🟩 BASE_DIR.parent:", BASE_DIR.parent)
print("🟨 Files at BASE_DIR.parent:", os.listdir(BASE_DIR.parent))
print("🟧 Files at /opt/render/project/src:", os.listdir("/opt/render/project/src"))
